config/routes.rb
Rails.application.routes.draw do
  get 'purposes/new'
  devise_for :users
  get 'payments_balances/index'
  root to: "payments_balances#index"
  resources :payments_balances, format: false do
    collection do
      get :show, format: false
      get :edit, format: false
    end
  end
  resources :purposes, only:[:new, :edit], shallow: true
  get 'purpose/:id', to: 'purposes#search'
  resources :users, only: [:show, :edit, :update]
  # resources :passwords, only: [:new, :create, :edit, :update]
end

app/models/payments_balance.rb
class PaymentsBalance < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  
  with_options presence: true do
    validates :date
    validates :amount
    validates :payment_id, numericality: { other_than: 0, message: "が選択されていません" }
  end
  
  has_many   :users, through: :budgets
  belongs_to :purpose
  belongs_to :payment

  def self.total_amount_by_date(date)
    where(date: date).sum(:amount)
  end

  #バリデーションの重複撤去
  def remove_unnecessary_error_messages
    errors.messages.delete(:payments_balance)
  end
end

app/controllers/payments_balances_controller.rb
class PaymentsBalancesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_payments_balance, only: [:edit, :show, :update]
  before_action :new_form_ids, only: :update
  before_action :no_found_page, only: :show
  before_action :amount_calculation, only: :index
  before_action :day_amount_calculation, only: :show
  before_action :user_data, only: [:index, :new, :edit, :show]

  def index
    @payments_balances = PaymentsBalance.where(user_id: current_user.id)
    payments_balance_id = params[:payments_balance_id]
    date = params[:date]
  end

  def new
    @form = Form::PaymentsBalanceCollection.new
    @purpose = Purpose.new
    @main_purpose = Purpose.all.order("id ASC").limit(2)
  end

  def create
    @form = Form::PaymentsBalanceCollection.new(payments_balance_params)
    if @form.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @selected_purpose_ids = @payments_balance.map { |balance| balance.purpose.path_ids }
  end

  def update
    ids = params[:id].split(',').map(&:to_i)
    if params[:payments_balance] && params[:payments_balance][:payments_balances]
      attributes = params[:payments_balance][:payments_balances].values
      existing_form_ids = attributes.map { |nested_hash| nested_hash["id"].to_i }
      deleted_form_ids = ids - existing_form_ids
      attributes.each do |value|
        purpose_id = value["purpose_id"]
        parent_id = Purpose.find(purpose_id).root_id
        ancestry = Purpose.find(purpose_id).ancestry
        # valueハッシュに更新したデータを格納
        value["parent_id"] = parent_id
        value["ancestry"] = ancestry
      end
      # 既存フォーム更新
      if @payments_balance.update(existing_form_ids, attributes)
        # 既存フォーム削除
        PaymentsBalance.where(id: deleted_form_ids).destroy_all
        redirect_to payments_balances_path(date: @selected_date)
      else
        render :edit
      end
    else
      # 既存フォーム全削除
      PaymentsBalance.where(id: ids).destroy_all
      # 新規フォーム作成
      redirect_to payments_balances_path(date: @selected_date)
    end    
  end  
  
  def show
  end

  private
  
  def payments_balance_params
    params.require(:form_payments_balance_collection)
          .permit(:date, payments_balances_attributes: [:date, :amount, :payment_id, :ancestry, :parent_id, :purpose_id])
    .merge(user_id: current_user.id)
  end

  def set_payments_balance
    @selected_date = Date.parse(params[:date])
    @payments_balance = PaymentsBalance.where(date: @selected_date, user_id: current_user.id)
    @payments_balances = PaymentsBalance.where(user_id: current_user.id)
  end

  def new_form_ids
    if params.key?(:form_payments_balance_collection)
      new_form_ids = Form::PaymentsBalanceCollection.new(payments_balance_params)
      unless new_form_ids.save
        render :edit
      end
    end
  end

  def no_found_page
    if @payments_balance.none?
      redirect_to root_path
    end
  end

  def get_amount
    @amount = PaymentsBalance.where(amount: amount).all.to_json
  end

  def amount_calculation
    # 現金
    @cash_plus = PaymentsBalance.where("date <= ? AND user_id = ? AND payment_id = ? AND parent_id = ?", Time.zone.now, current_user.id, 1, 1).sum(:amount) 
    @cash_minus = PaymentsBalance.where("date <= ? AND user_id = ? AND payment_id = ? AND parent_id = ?", Time.zone.now, current_user.id, 1, 2).sum(:amount)
    @cash_input = PaymentsBalance.where("date <= ? AND user_id = ? AND payment_id = ? AND parent_id = ?", Time.zone.now, current_user.id, 1, 3).sum(:amount)
    @cashless_charge = PaymentsBalance.where("date <= ? AND user_id = ? AND payment_id = ? AND parent_id = ?", Time.zone.now, current_user.id, 1, 4).sum(:amount) 
    # クレジット決済
    @debt_num_past = PaymentsBalance.where("date <= ? AND user_id = ? AND payment_id = ? AND parent_id = ?", Time.zone.now, current_user.id, 2, 2).sum(:amount) 
    @debt_num_future = PaymentsBalance.where("date > ? AND user_id = ? AND parent_id = ?", Time.zone.now, current_user.id, 2).sum(:amount) 
    # 口座振込
    @atm_plus = PaymentsBalance.where("date <= ? AND user_id = ? AND payment_id = ? AND parent_id = ?", Time.zone.now, current_user.id, 3, 1).sum(:amount) 
    @atm_minus = PaymentsBalance.where("date <= ? AND user_id = ? AND payment_id = ? AND parent_id = ?", Time.zone.now, current_user.id, 3, 2).sum(:amount)
    @cash_output = PaymentsBalance.where("date <= ? AND user_id = ? AND payment_id = ? AND parent_id = ?", Time.zone.now, current_user.id, 3, 3).sum(:amount)
    @atm_charge = PaymentsBalance.where("date <= ? AND user_id = ? AND payment_id = ? AND parent_id = ?", Time.zone.now, current_user.id, 3, 4).sum(:amount) 
    # 合計値を表示
    @sum_cash = @cash_minus + @cash_input + @cashless_charge - @cash_plus - @cash_output
    @sum_atm = @atm_minus + @debt_num_past + @cash_output + @atm_charge - @atm_plus - @cash_input
  end

  def day_amount_calculation
    # 現金
    @cash_plus = PaymentsBalance.where("date = ? AND user_id = ? AND payment_id = ? AND parent_id = ?", @selected_date, current_user.id, 1, 1).sum(:amount) 
    @cash_minus = PaymentsBalance.where("date = ? AND user_id = ? AND payment_id = ? AND parent_id = ?", @selected_date, current_user.id, 1, 2).sum(:amount)
    @cash_input = PaymentsBalance.where("date = ? AND user_id = ? AND payment_id = ? AND parent_id = ?", @selected_date, current_user.id, 1, 3).sum(:amount)
    @cashless_charge = PaymentsBalance.where("date = ? AND user_id = ? AND payment_id = ? AND parent_id = ?", @selected_date, current_user.id, 1, 4).sum(:amount) 
    # クレジット決済
    @debt_num_past = PaymentsBalance.where("date = ? AND user_id = ? AND payment_id = ? AND parent_id = ?", @selected_date, current_user.id, 2, 2).sum(:amount) 
    # 口座振込
    @atm_plus = PaymentsBalance.where("date = ? AND user_id = ? AND payment_id = ? AND parent_id = ?", @selected_date, current_user.id, 3, 1).sum(:amount) 
    @atm_minus = PaymentsBalance.where("date = ? AND user_id = ? AND payment_id = ? AND parent_id = ?", @selected_date, current_user.id, 3, 2).sum(:amount)
    @cash_output = PaymentsBalance.where("date = ? AND user_id = ? AND payment_id = ? AND parent_id = ?", @selected_date, current_user.id, 3, 3).sum(:amount)
    @atm_charge = PaymentsBalance.where("date = ? AND user_id = ? AND payment_id = ? AND parent_id = ?", @selected_date, current_user.id, 3, 4).sum(:amount) 
    # 合計値を表示
    @total_income = @cash_plus + @atm_plus
    @total_expend = @cash_minus + @atm_minus + @debt_num_past + @atm_charge + @cashless_charge
  end

  def user_data
    @user = current_user
  end
end

app/helpers/payments_balances_helper.rb
module PaymentsBalancesHelper
  def edit_link_for_date(date)
    edit_payments_balance_path(date: date)
  end

  #   # ヘルパー

  module AmountHelper
    def number_to_currency(amount_num)
      "#{amount_num.to_s(:delimited, delimiter: ',')}"
    end
  end
  # ヘルパーメソッドを修正
  def render_child_categories(parent_id, child_id, grandchild_id, index)
    # データベースから与えられた parent_id に対する子カテゴリーオブジェクトを取得
    parent_category = Purpose.find(parent_id)
    child_categories = parent_category.children

    grandchild_categories = []
    if child_id.present?
      selected_child_category = Purpose.find(child_id)
      grandchild_categories = selected_child_category.children
    end

    # プルダウンメニューのHTMLを生成
    html = "
    <td id='edit-child-select-wrap-#{index}' class='c_select_w'>
    <select id='edit-child-select-#{index}' class='c_select' name='payments_balance[payments_balances][#{index}][purpose_id]'>"
    child_categories.each do |child|
      selected = child.id == child_id ? "selected" : ""
      html += "<option value='#{child.id}' #{selected}>#{child.name}</option>"
    end

    html += "</select></td>"

    if grandchild_categories.any?
      html += "
      <td id='edit-grand-child-select-wrap-#{index}' class='c_select_w'>
      <select id='edit-grand-child-select-#{index}' class='c_select' name='payments_balance[payments_balances][#{index}][purpose_id]'>"
      grandchild_categories.each do |grandchild|
        selected = grandchild.id == grandchild_id ? "selected" : ""
        html += "<option value='#{grandchild.id}' #{selected}>#{grandchild.name}</option>"
      end
      html += "</select></td>"
    end

    return html.html_safe
  end
end

app/views/payments_balances/edit.html.erb
<%= render "devise/shared/header" %>

<h2>List Update</h2>
<%= form_with model: @payments_balance, url: payments_balance_path(date: @selected_date), method: :patch, id: "pb-form", local: true do |form| %>
  <div class="data_field">
    <%= form.label :date, 'Date:' %>
    <%= @selected_date %>
  </div>
  
  <button type="button" class="add-form" id="add-form-button">+</button>
  <div class="balance_forms" id="form-area">
  <% @payments_balance.each_with_index do |balance, index| %>
    <table class="payments_balance_table" cellspacing="0">
    <thead class="tb_columns">
      <tr class="tb_column">
        <th class="tb_date">    日付     </th>
        <th class="tb_purpose"> 使用目的 </th>
        <th class="tb_amount">  金額     </th>
        <th class="tb_payment"> 決済方法 </th>
        <th class="tb_delete"></th>
      </tr>
    </thead>
    <tbody class="balances_list">
      <%= form.fields_for :payments_balances, balance, index: index do |pb| %>
      <%= render 'devise/shared/error_messages', model: balance %> 
        <div id="payments-balance-data" data-payment-count="<%= @payments_balances.count %>">
          <tr class="balance_forms">
            <td class="balance_form_date"><%= pb.date_field :date, type: "date", value: @selected_date, class: "form_date", id:"inputform-date-#{index}" %></td>
              <td class="balance_form_purpose" id="edit-select-purpose-<%= index %>">
                <%= collection_select :payments_balance, :purpose_id, Purpose.roots, :id, :name, { include_blank: "---", selected: @selected_purpose_ids[index] }, { id: "edit-parent-category-#{index}", class: "form_purpose" } %>
              </td>
            <td class="balance_form_amount"><%= pb.text_field :amount, class: "form_amount", placeholder: "0", type: "number", style: "text-align:right", id:"inputform-amount-#{index}" %></td>
            <td class="balance_form_payment"><%= pb.collection_select(:payment_id, Payment.all, :id, :name, {}, {class: "form_payment", id:"payment-category-#{index}"}) %></td>
            <td class="balance_form_delete"><button type="button" class="delete-form", id="deleted-form-ids">
            <%= link_to "", payments_balance_path(balance.id), method: :delete %>×</button></td>
            <%= pb.hidden_field :id %>
          </tr>
        </div>
      <% end %>
    <% end %>
    </tbody>
  </table>
  <script>
    let purpose_ids = <%= @selected_purpose_ids %>;
    let annual_income = <%= @user.annual_income %>;
  </script>
  </div>
  <div class="setting_menu">
    <%= image_tag "メモアイコン.png", size: "20x20" %>
    <span class="deactive_btn" id="update-button-deactive">更新</span>
    <%= form.submit "更新", class: "save_btn", id: "update-button" %>
    <div class="back">
      <%= image_tag "Uターン矢印 1.png", size: "20x20" %>
      <%= link_to "戻る", payments_balance_path(date: @selected_date), class: "back_btn" %>
    </div>
  </div>
  
<% end %>

app/views/payments_balances/index.html.erb
<%= render "devise/shared/header" %>

<div class="current_mode" id="mode_select">
  <div class="mode_select_menu">
    <select class="payment_select_box" id="payments_mode" change="paymentSel()">
      <option value="1">💴</option>
      <option value="2">💳</option>
      <option value="3">🏧</option>
    </select>
    <div class="mode_name" id="mode-name">現金残高</div>
  </div>

  <script>
    let annual_income = <%= @user.annual_income %>;
    let cash_cons = <%= @user.cash - @sum_cash - @user.cash_over_short %>;
    let debt_future = <%= @debt_num_future + @user.debt %>;
    let atm_cons = <%= @user.savings - @sum_atm %>
  </script>

  <div class="cash_num">
    <div class="canvas_views" id="num-counter">
      <div class="canvas_view">
        <div class="current_num" data_num ="<%= @user.cash - @sum_cash - @user.cash_over_short %>" id="cash-current-num">0</div>
        <div class="current_num" data_num ="<%= @debt_num_future + @user.debt %>" id="debt-current-num">0</div> 
        <div class="current_num" data_num ="<%= @user.savings - @sum_atm %>" id="savings-current-num">0</div> 
      </div>
      <div class="bar_view" id="money-bar">
        <div id="canvas-frame-2">
          <div id="canvas-2"></div>
          </div>
        <div class="num_view">
          <div id="low_num"></div>
          <div id="tank"></div>
          <div id="alert"></div>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="setting_nav">
  <div class="new_list">
    <%= image_tag "鉛筆ボタン.png", size: "20x20" %>
    <%= link_to "新規登録", new_payments_balance_path, class: "post" %>
  </div>
  <%# <%= link_to "グラフ", "#", class: "post" %> <%# 追加実装フェイズで実装 %>
  <div class="option_menu_bar" id="option-menu">
  
  <ul class="menu_elements">設定
    <li class="pull-down-list">
      <%= image_tag "おこづかいアイコン1.png", size: "20x25" %>
      <%= link_to "金銭情報", "/users/#{current_user.id}" %>
    </li>
    <li class="pull-down-list">
      <%= image_tag "9736.png", size: "20x25" %>
      <%= link_to "アカウント情報変更", edit_user_registration_path %>
    </li>
  </ul>
<div>

<% day_number = 0 %>

<%= month_calendar event: @payments_balances do |date, _| %>
  <div id="payments-balance-data" data-payment-count="<%= @payments_balances.count %>">
    <% count_amount = PaymentsBalance.where(date: date, user_id: current_user.id).count %>
    <% unless count_amount.zero? %>
      <%= link_to date.day, payments_balances_path(date: date), class: "date_info" %><br/>
      <% total_income = PaymentsBalance.where(date: date, user_id: current_user.id, parent_id: purpose_id = 1).sum(:amount) %>
      <% total_expend = PaymentsBalance.where(date: date, user_id: current_user.id, parent_id: purpose_id = 2).sum(:amount) %>
      <% total_charge = PaymentsBalance.where(date: date, user_id: current_user.id, parent_id: purpose_id = 4).sum(:amount) %>
      <% total_amount = total_expend + total_charge - total_income %>
      <div class="sum_amount_num" id="amount-num-<%= day_number %>">
        <%= total_amount.to_s(:delimited, delimiter: ',') %>
      </div>
      <% count_amount = PaymentsBalance.where(date: date, user_id: current_user.id).count(:amount) %>
      <div class="count_amount_num">
      <%= image_tag "キュートながま口財布アイコン.png", size: "20x20" %><%= count_amount %>
      </div>
    <% else %>
      <span class="date_no_info"><%= date.day %></span>
    <% end %>
  </div>
  <% day_number += 1 %>
<% end %>

app/views/payments_balances/new.html.erb
<%= render "devise/shared/header" %>

<h2>List Registration</h2>
<%= form_with model: @form, url: payments_balances_path, id: "pb-form", local: true do |form| %>
<%= render 'devise/shared/error_messages', model: @form %>
  <button type="button" class="add-form" id="add-form-button">+</button>
  <table class="payments_balance_table" cellspacing="0">
    <thead class="tb_columns">
      <tr class="tb_column">
        <th class="tb_date">    日付     </th>
        <th class="tb_purpose"> 使用目的 </th>
        <th class="tb_amount">  金額     </th>
        <th class="tb_payment"> 決済方法 </th>
        <th class="tb_delete"></th>
      </tr>
    </thead>
    <tbody class="balances_list">
      <%= form.fields_for :payments_balances do |balance| %>
        <tr class="balance_forms">
          <td class="balance_form_date"><%= balance.date_field :date, type: "date", class: "form_date", id:"inputform-date-0" %></td>
          <td class="balance_form_purpose" id="new-select-purpose-0"><%= balance.collection_select :purpose_id, Purpose.roots, :id, :name, { include_blank: "---" }, { id: "new-parent-category-0", class: "form_purpose" } %></td>
          <td class="balance_form_amount"><%= balance.text_field :amount, class: "form_amount", placeholder: "0", type: "number", style: "text-align:right", id: "inputform-amount-0" %></td>
          <td class="balance_form_payment"><%= balance.collection_select(:payment_id, Payment.all, :id, :name, {}, {class: "form_payment", id:"payment-category-0"}) %></td>
          <td class="balance_form_delete"><button type="button" class="delete-form" id="deleted-form-ids" data-form_id="form-0">×</button></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <script>
    let annual_income = <%= @user.annual_income %>;
  </script>
  <div class="balance_forms" id="form-area"></div>
  <div class="setting_menu">
    <%= image_tag "メモアイコン.png", size: "20x20" %>
    <span class="deactive_btn" id="save-button-deactive">登録</span>
    <%= form.submit "登録", class: "save_btn", id: "save-button" %>
    <div class="back">
      <%= image_tag "Uターン矢印 1.png", size: "20x20" %>
      <%= link_to "戻る", root_path, class: "back_btn" %>
    </div>
  </div>
<% end %>

app/views/payments_balances/show.html.erb
<%= render "devise/shared/header" %>

<h2>Payments Balance List (<%= @selected_date %>)</h2>

<% pb_num = 0 %>

<% if @payments_balance.any? %>
  <table class="show_payments" cellspacing="0">
    <thead>
      <tr>
        <th class="show_tb_purpose"> 使用目的 </th>
        <th class="show_tb_amount">  金額     </th>
        <th class="show_tb_payment"> 決済方法 </th>
      </tr>
    </thead>
    <tbody>
      <% @payments_balance.each do |balance| %>
        <tr>
          <td class="blance_propuse" style="text-align:left">
            <% balance.purpose.ancestors.each do |category| %>
              <span><%= category.name %></span>
              <span>,</span>
            <% end %>
            <span><%= balance.purpose.name %></span>
          </td>
          <td class="blance_amount" style="text-align:right">
          <% if balance.parent_id == 2 || balance.parent_id == 4 %>
            <span id="pb-amount-num-<%= pb_num %>"><%= balance.amount.to_s(:delimited, delimiter: ',') %></span>
          <% else %>
            <span><%= balance.amount.to_s(:delimited, delimiter: ',') %></span>
          <% end %>
          </td>
          <td class="blance_payment">
            <%= balance.payment.name %>
          </td>
        </tr>
        <% pb_num += 1 %>
      <% end %>
    </tbody>
  </table>

  <table class="total_payments" cellspacing="0">
    <thead>
      <tr>
        <th class="tb_income"> 収入 </th>
        <th class="tb_expend"> 支出 </th>
        <th class="tb_total_amount"> 合計 </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="income" id="income-num" style="text-align:right">
          <%= @total_income.to_s(:delimited, delimiter: ',') %>
        </td>
        <td class="expend" id="expend-num" style="text-align:right">
          <%= @total_expend.to_s(:delimited, delimiter: ',') %> 
        </td>
        <td class="total_amount" id="total-amount-num" style="text-align:right">
           <%= total_amount = (@total_expend.to_i - @total_income.to_i).to_s(:delimited, delimiter: ',') %>
        </td>
      </tr>
    </tbody>
  </table>
  <script>
    let annual_income = <%= @user.annual_income %>;
  </script>
<% else %>
  <p>No data found.</p>
<% end %>
<div class="setting_menu">
  <div class="edit">
    <%= image_tag "メモアイコン.png", size: "20x20" %>
    <%= link_to "編集", edit_payments_balance_path(date: @selected_date, id: @payments_balance.pluck(:id).join(',')), class: "edit_btn" %>
  </div>
  <div class="back">
    <%= image_tag "Uターン矢印 1.png", size: "20x20" %>
    <%= link_to "戻る", root_path, class: "back_btn" %>
  </div>
</div>

  